### ISSUE TITLE
CreateClient<TClient> Naming Issue

### ISSUE THREAD

**Issue by gorillapower** [agertenbach/Ringleader#4] opened 2024-11-15 10:29 UTC
I encountered an issue when my Typed HttpClient was using a generic type. In my example `.AddHttpClient<GenericClient<MyName>>` produced "GenericClient\`1" in the `IContextualHttpClientFactory.CreateClient<TClient>(string handlerContext))` method

![image](https://github.com/user-attachments/assets/32c76775-3bf7-4ad2-b8dd-dc99dc0ab905)

This caused issues as I was expecting the name to be `GenericClient<MyName>`. It looks like in .NET there is an internal method that resolves the TClient name string. See this code [string name = TypeNameHelper.GetTypeDisplayName(typeof(TClient), fullName: false);](https://github.com/dotnet/runtime/blob/e5129e5323155feec25cd75e8d67986b601921d1/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L409)

I resolved the issue by creating my own `IContextualHttpClientFactory` and creating the CreateClient to look like this

```csharp
    public TClient CreateClient<TClient>(string handlerContext)
    {
        var client = CreateClient(typeof(TClient).FullName, handlerContext);
        return _serviceProvider.GetRequiredService<ITypedHttpClientFactory<TClient>>().CreateClient(client);
    }
```

This resolved the FullName with the generic type included.

**UPDATE**: This solution did not work, the `TClient` needs to resemble the exact name that the internal AddHttpClient<TClient> would create, being `GenericClient<MyName>`. 

What did end up working was to replicate the `TypeNameHelper.GetTypeDisplayName()`  code referenced above. Working Example.
```csharp
    public TClient CreateClient<TClient>(string handlerContext)
    {
         string name = TypeNameHelper.GetTypeDisplayName(typeof(TClient), fullName: false);
         var client = CreateClient(name, handlerContext);
        return _serviceProvider.GetRequiredService<ITypedHttpClientFactory<TClient>>().CreateClient(client);
    }
```

**Comment by agertenbach** [comment] 2024-11-18 15:52
Thanks for the report, issue confirmed.

I have a pending branch and PR to address this issue along with additions to properly handle typed clients with interfaces and some other small quality of life updates.

**Comment by agertenbach** [comment] 2024-11-19 00:08
3.0.0-rc is available here and as a pre-release package on Nuget. It has a major version increment due to some small changes on interfaces.

The issue you reported is addressed by a new wrapper type called `TypedClientSignature` that uses an internal implementation of `TypeNameHelper` and has implicit conversion to and from a string to maintain existing comparison logic.

In addition to resolving issues with typed clients with a generic parameter, the handler factory logic now supports 

`client.IsTypedClient<TypedClient>()`

in favor of (but optionally in addition to the potentially inaccurate)

`client == typeof(TypedClient).Name`

Let me know if you have any issues with the RC, will plan to merge this week.

**Closed as completed** 2024-11-25 13:34 UTC
